language: python
python:
  - "2.7"
script: ./runtests.sh
env:
  - DJANGO_VERSION=1.6.8
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.2

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - python setup.py -q install
